# Generated by Django 4.2 on 2023-04-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='correta',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='msg_correta',
            field=models.TextField(default='Mensagem Errada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='msg_errada',
            field=models.TextField(default='Mensagem errada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='msg_neutra',
            field=models.TextField(default='Mensagem Neutra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='opcao1',
            field=models.TextField(default='Opção 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='opcao2',
            field=models.TextField(default='Opção 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='opcao3',
            field=models.TextField(default='Opção 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='opcao4',
            field=models.TextField(default='Opção 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questao',
            name='pergunta',
            field=models.TextField(default='Pergunta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
